packages:
  - storybook

allowBuilds:
  esbuild: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@aexae/comete-design-tokens'
  - '@aexae/comete-icons'
  - '@aexae/comete-logos'
  - '@aexae/comete-illustrations'
