declare const styles: {
  readonly "body": string;
  readonly "container": string;
  readonly "divider": string;
  readonly "empty": string;
  readonly "emptyAction": string;
  readonly "emptyDescription": string;
  readonly "emptyIcon": string;
  readonly "emptyText": string;
  readonly "emptyTitle": string;
  readonly "footer": string;
  readonly "footerBrand": string;
  readonly "header": string;
  readonly "headerAppName": string;
  readonly "headerContent": string;
  readonly "headerLogo": string;
  readonly "headerSubtitle": string;
  readonly "iconAfter": string;
  readonly "iconBefore": string;
  readonly "item": string;
  readonly "itemContent": string;
  readonly "itemDescription": string;
  readonly "itemDisabled": string;
  readonly "itemSelected": string;
  readonly "itemTitle": string;
  readonly "section": string;
  readonly "sectionHeading": string;
  readonly "sideNav": string;
  readonly "skeletonHeader": string;
  readonly "skeletonHeaderContent": string;
  readonly "skeletonItem": string;
  readonly "skeletonItemContent": string;
  readonly "skeletonSectionTitle": string;
};
export = styles;

