declare const styles: {
  readonly "heading-large": string;
  readonly "heading-medium": string;
  readonly "heading-small": string;
  readonly "heading-xlarge": string;
  readonly "heading-xsmall": string;
  readonly "heading-xxlarge": string;
  readonly "heading-xxsmall": string;
  readonly "hero-large": string;
  readonly "hero-medium": string;
  readonly "hero-small": string;
  readonly "hero-xlarge": string;
  readonly "hero-xsmall": string;
  readonly "hero-xxlarge": string;
  readonly "hero-xxsmall": string;
  readonly "text-large-bold": string;
  readonly "text-large-medium": string;
  readonly "text-large-regular": string;
  readonly "text-medium-bold": string;
  readonly "text-medium-medium": string;
  readonly "text-medium-regular": string;
  readonly "text-small-bold": string;
  readonly "text-small-medium": string;
  readonly "text-small-regular": string;
  readonly "text-xsmall-bold": string;
  readonly "text-xsmall-medium": string;
  readonly "text-xsmall-regular": string;
};
export = styles;

